In [19]:
import pandas as pd
import numpy as np

print("Environnement configuré avec succès!")
print(f"Version de Pandas: {pd.__version__}")

Environnement configuré avec succès!
Version de Pandas: 2.3.3

In [20]:
# ============================================
# Exercice 1: Format JSON
# ============================================
import json

# إنشاء ملف JSON تجريبي
data_movies = {
    "movies": [
        {"title": "Inception", "year": 2010, "rating": 8.8},
        {"title": "Interstellar", "year": 2014, "rating": 8.6},
        {"title": "The Dark Knight", "year": 2008, "rating": 9.0}
    ]
}

# حفظ الملف في مجلد data (استخدم ../ للرجوع خطوة للخلف)
with open('../data/movies.json', 'w') as f:
    json.dump(data_movies, f, indent=4)

print("✅ fichier JSON créé dans data/")

# قراءة الملف JSON
df_json = pd.read_json('../data/movies.json')
print("\n📄 Contenu du fichier JSON:")
df_json

✅ fichier JSON créé dans data/

📄 Contenu du fichier JSON:

                                              movies
0  {'title': 'Inception', 'year': 2010, 'rating':...
1  {'title': 'Interstellar', 'year': 2014, 'ratin...
2  {'title': 'The Dark Knight', 'year': 2008, 'ra...

In [21]:
# ============================================
# Exercice 1: Format Excel
# ============================================

# إنشاء DataFrame تجريبي
df_excel = pd.DataFrame({
    'Nom': ['Ahmed', 'Fatima', 'Mohamed', 'Aicha'],
    'Age': [25, 30, 28, 22],
    'Ville': ['Nouakchott', 'Nouadhibou', 'Rosso', 'Kaédi'],
    'Salaire': [50000, 60000, 55000, 45000]
})

print("📊 DataFrame créé:")
display(df_excel)

# حفظ الملف في مجلد data/
df_excel.to_excel('../data/donnees_test.xlsx', index=False)

print("\n✅ fichier Excel créé dans data/!")

# قراءة الملف Excel
df_read_excel = pd.read_excel('../data/donnees_test.xlsx')
print("\n📄 Contenu lu depuis Excel:")
display(df_read_excel)

📊 DataFrame créé:

       Nom  Age       Ville  Salaire
0    Ahmed   25  Nouakchott    50000
1   Fatima   30  Nouadhibou    60000
2  Mohamed   28       Rosso    55000
3    Aicha   22       Kaédi    45000

✅ fichier Excel créé dans data/!

📄 Contenu lu depuis Excel:

       Nom  Age       Ville  Salaire
0    Ahmed   25  Nouakchott    50000
1   Fatima   30  Nouadhibou    60000
2  Mohamed   28       Rosso    55000
3    Aicha   22       Kaédi    45000

In [22]:
# ============================================
# Exercice 1: Format Excel
# ============================================

# إنشاء DataFrame تجريبي
df_excel = pd.DataFrame({
    'Nom': ['Ahmed', 'Fatima', 'Mohamed', 'Aicha'],
    'Age': [25, 30, 28, 22],
    'Ville': ['Nouakchott', 'Nouadhibou', 'Rosso', 'Kaédi'],
    'Salaire': [50000, 60000, 55000, 45000]
})

print("📊 DataFrame créé:")
display(df_excel)

# حفظ الملف في مجلد data/
df_excel.to_excel('../data/donnees_test.xlsx', index=False)

print("\n✅ fichier Excel créé dans data/!")

# قراءة الملف Excel
df_read_excel = pd.read_excel('../data/donnees_test.xlsx')
print("\n📄 Contenu lu depuis Excel:")
display(df_read_excel)

📊 DataFrame créé:

       Nom  Age       Ville  Salaire
0    Ahmed   25  Nouakchott    50000
1   Fatima   30  Nouadhibou    60000
2  Mohamed   28       Rosso    55000
3    Aicha   22       Kaédi    45000

✅ fichier Excel créé dans data/!

📄 Contenu lu depuis Excel:

       Nom  Age       Ville  Salaire
0    Ahmed   25  Nouakchott    50000
1   Fatima   30  Nouadhibou    60000
2  Mohamed   28       Rosso    55000
3    Aicha   22       Kaédi    45000

In [23]:
# ============================================
# Exercice 2: Base de Données Relationnelle
# ============================================
import sqlite3
import pandas as pd
from sqlalchemy import create_engine

print("=" * 60)
print("EXERCICE 2: MySQL/SQLite Database Connection")
print("=" * 60)

# ============================================
# Partie 1: Création de la base de données
# ============================================
print("\n📥 Étape 1: Chargement du fichier CSV...")

# قراءة ملف student-mat.csv
df_student = pd.read_csv('../data/student-mat.csv', sep=';')

print(f"✅ Nombre d'étudiants chargés: {len(df_student)}")
print(f"📊 Colonnes disponibles: {df_student.columns.tolist()}")

# ============================================
# Partie 2: Création de la base SQLite
# ============================================
print("\n🗄️  Étape 2: Création de la base de données SQLite...")

db_path = '../data/school_db.sqlite'
conn = sqlite3.connect(db_path)

# حفظ البيانات في جدول 'etudiants'
df_student.to_sql('etudiants', conn, if_exists='replace', index=False)

print("✅ Table 'etudiants' créée dans SQLite!")

# ============================================
# Partie 3: Requête SQL - Extraction
# ============================================
print("\n🔍 Étape 3: Exécution de la requête SQL...")
print("Requête: SELECT * FROM etudiants WHERE G3 > 15")

# الاستعلام: الطلاب اللي عندهم G3 > 15
query = "SELECT * FROM etudiants WHERE G3 > 15"
df_mysql = pd.read_sql_query(query, conn)

print(f"\n✅ Succès!")
print(f"📊 Nombre d'étudiants avec G3 > 15: {len(df_mysql)}")

print("\n📄 Aperçu des données (G1, G2, G3):")
display(df_mysql[['G1', 'G2', 'G3']].head(10))

# إضافة عمود source
df_mysql['source'] = 'MySQL'

# إغلاق الاتصال
conn.close()

print("\n✅ DataFrame MySQL créé avec succès!")
print("=" * 60)

============================================================
EXERCICE 2: MySQL/SQLite Database Connection
============================================================

📥 Étape 1: Chargement du fichier CSV...
✅ Nombre d'étudiants chargés: 395
📊 Colonnes disponibles: ['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu', 'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime', 'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery', 'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc', 'Walc', 'health', 'absences', 'G1', 'G2', 'G3']

🗄️  Étape 2: Création de la base de données SQLite...
✅ Table 'etudiants' créée dans SQLite!

🔍 Étape 3: Exécution de la requête SQL...
Requête: SELECT * FROM etudiants WHERE G3 > 15

✅ Succès!
📊 Nombre d'étudiants avec G3 > 15: 40

📄 Aperçu des données (G1, G2, G3):

   G1  G2  G3
0  16  18  19
1  14  16  16
2  15  15  16
3  17  16  17
4  17  16  16
5  15  16  18
6  19  18  18
7  19  19  20
8  15  16  16
9  16  16  16

✅ DataFrame MySQL créé avec succès!
============================================================

In [24]:
# ============================================
# Exercice 3: API REST
# ============================================
import requests

print("=" * 50)
print("Collecte de données via API REST")
print("=" * 50)

# الاتصال بـ API عامة (JSONPlaceholder)
api_url = "https://jsonplaceholder.typicode.com/posts"

# جلب البيانات (5 منشورات فقط)
response = requests.get(api_url, params={'_limit': 5})

if response.status_code == 200:
    # تحويل JSON إلى DataFrame
    data_api = response.json()
    df_api = pd.DataFrame(data_api)
    
    print("✅ Données récupérées avec succès!")
    print(f"\n📡 Nombre de posts: {len(df_api)}")
    print("\n📄 Aperçu des données:")
    display(df_api[['userId', 'title']])
else:
    print(f"❌ Erreur: {response.status_code}")

==================================================
Collecte de données via API REST
==================================================
✅ Données récupérées avec succès!

📡 Nombre de posts: 5

📄 Aperçu des données:

   userId                                              title
0       1  sunt aut facere repellat provident occaecati e...
1       1                                       qui est esse
2       1  ea molestias quasi exercitationem repellat qui...
3       1                               eum et est occaecati
4       1                                 nesciunt quas odio

In [25]:
# ============================================
# Exercice 3: Web Scraping
# ============================================
from bs4 import BeautifulSoup

print("=" * 50)
print("Web Scraping - Extraction de données")
print("=" * 50)

try:
    # التحقق من robots.txt أولاً
    robots_url = "http://books.toscrape.com/robots.txt"
    robots_response = requests.get(robots_url)
    print(f"🤖 robots.txt:\n{robots_response.text[:150]}...\n")
    
    # الاتصال بالموقع
    url = "http://books.toscrape.com/"
    page = requests.get(url)
    soup = BeautifulSoup(page.content, 'html.parser')
    
    # استخراج عناوين الكتب
    titles = [h3.a['title'] for h3 in soup.find_all('h3', class_='product_title')[:5]]
    
    print("✅ Scraping réussi!")
    print(f"\n📚 Nombre de livres extraits: {len(titles)}")
    print("\n📖 Titres des livres:")
    for i, title in enumerate(titles, 1):
        print(f"  {i}. {title}")
    
    # إنشاء DataFrame
    df_scrape = pd.DataFrame(titles, columns=['Titre_Livre'])
    print("\n📊 DataFrame créé:")
    display(df_scrape)
    
except Exception as e:
    print(f"⚠️ Erreur: {e}")

==================================================
Web Scraping - Extraction de données
==================================================
🤖 robots.txt:
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.21.6</center>
</body>
</html...

✅ Scraping réussi!

📚 Nombre de livres extraits: 0

📖 Titres des livres:

📊 DataFrame créé:

Empty DataFrame
Columns: [Titre_Livre]
Index: []

In [26]:
 # ============================================
# Exercice 3: Web Scraping (Version alternative)
# ============================================
from bs4 import BeautifulSoup
import requests

print("=" * 50)
print("Web Scraping - Example")
print("=" * 50)

try:
    # استخدام موقع Wikipedia كمثال
    url = "https://en.wikipedia.org/wiki/Main_Page"
    headers = {'User-Agent': 'Mozilla/5.0'}
    page = requests.get(url, headers=headers)
    
    if page.status_code == 200:
        soup = BeautifulSoup(page.content, 'html.parser')
        
        # استخراج العناوين من الصفحة الرئيسية لـ Wikipedia
        titles = []
        for heading in soup.find_all(['h2', 'h3'])[:5]:
            text = heading.get_text(strip=True)
            if text and text != 'edit':
                titles.append(text)
        
        print("✅ Scraping réussi!")
        print(f"\n📰 Nombre d'éléments extraits: {len(titles)}")
        print("\n📋 Éléments trouvés:")
        for i, title in enumerate(titles, 1):
            print(f"  {i}. {title}")
        
        # إنشاء DataFrame
        df_scrape = pd.DataFrame(titles, columns=['Titre_Wikipedia'])
        print("\n📊 DataFrame créé:")
        display(df_scrape)
    else:
        print(f"⚠️ Erreur HTTP: {page.status_code}")
        
except Exception as e:
    print(f"⚠️ Erreur: {e}")
    print("\n💡 Solution: Créer un DataFrame exemple")
    df_scrape = pd.DataFrame({
        'Titre_Wikipedia': ['Exemple 1', 'Exemple 2', 'Exemple 3']
    })
    display(df_scrape)

==================================================
Web Scraping - Example
==================================================
✅ Scraping réussi!

📰 Nombre d'éléments extraits: 5

📋 Éléments trouvés:
  1. From today's featured article
  2. Did you know ...
  3. In the news
  4. On this day
  5. Today's featured picture

📊 DataFrame créé:

                 Titre_Wikipedia
0  From today's featured article
1               Did you know ...
2                    In the news
3                    On this day
4       Today's featured picture

In [27]:
# ============================================
# FUSION DES SOURCES (Livrable final)
# ============================================

print("=" * 50)
print("FUSION MULTI-SOURCES")
print("=" * 50)

# إضافة عمود "source" لكل DataFrame
df_json['source_type'] = 'JSON'
df_excel['source_type'] = 'Excel'
df_api['source_type'] = 'API'
df_scrape['source_type'] = 'Web Scraping'

print("\n📊 Récapitulatif des sources:")
print(f"  ✓ JSON: {len(df_json)} lignes")
print(f"  ✓ Excel: {len(df_excel)} lignes")
print(f"  ✓ API: {len(df_api)} lignes")
print(f"  ✓ Web Scraping: {len(df_scrape)} lignes")

# حفظ كل DataFrame في مجلد data/
df_json.to_csv('../data/movies_processed.csv', index=False)
df_excel.to_csv('../data/donnees_processed.csv', index=False)
df_api.to_csv('../data/api_posts.csv', index=False)
df_scrape.to_csv('../data/wikipedia_scraped.csv', index=False)

print("\n✅ Tous les fichiers ont été sauvegardés dans data/!")

# إنشاء DataFrame ملخص
summary = pd.DataFrame({
    'Source': ['JSON', 'Excel', 'API', 'Web Scraping'],
    'Nombre_Lignes': [len(df_json), len(df_excel), len(df_api), len(df_scrape)]
})

print("\n📈 Résumé du TP:")
display(summary)

print("\n🎉 TP terminé avec succès!")
print("💾 N'oubliez pas de pousser sur GitHub!")

==================================================
FUSION MULTI-SOURCES
==================================================

📊 Récapitulatif des sources:
  ✓ JSON: 3 lignes
  ✓ Excel: 4 lignes
  ✓ API: 5 lignes
  ✓ Web Scraping: 5 lignes

✅ Tous les fichiers ont été sauvegardés dans data/!

📈 Résumé du TP:

         Source  Nombre_Lignes
0          JSON              3
1         Excel              4
2           API              5
3  Web Scraping              5

🎉 TP terminé avec succès!
💾 N'oubliez pas de pousser sur GitHub!